accumulative bug fix
PhasesResearchLab/dfttk-2021 pull request #1
Opened 2021-03-29 13:26 UTC by yiwang62

sorry for the huge amount accumulative update

2021-03-30 02:49 UTC, bocklund requested changes
1. Do we need the `tests/ExptData.json` file? It's a lot of added lines/data, but it isn't relevant to how DFTTK operates or runs.
2. I think I pointed out a few spots, but not all where we hardcode `>>db_file<<` and `>>vasp_cmd<<`. We should avoid doing everywhere and restore the original condition of *most* of the code where the arguments are passed by the caller. We should only make the `>>db_file<<` the default in a few key places.
3. 3. The test in `tests/test_QHA_failure` doesn't actually test DFTTK. It tests this particular class, `QHAAnalysis_failure`. If you change DFTTK's `QHAAnalysis` class to something totally different, that won't change whether this test passes or fails.

2021-03-30 02:49 UTC, bocklund commented on dfttk/EVcheck_QHA.py
> +        #vasp_cmd = env_chk(self.get('vasp_cmd', VASP_CMD), fw_spec)
Please delete commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/EVcheck_QHA.py
> +        #vasp_cmd = self['vasp_cmd']
Please delete commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/EVcheck_QHA.py
>          deformations = self.get('deformations', [])
We do not want to hard code `>>db_file<<` here because users may want to pass in their own `DB_FILE` and not use the method to look up the db file from the FWorker. 

I think the line `db_file = env_chk(self.get('db_file', DB_FILE), fw_spec)` does essentially the same thing as `>>db_file<<`, but allows users to pass in their own. Please look into this and fix all instances where `>>db_file<<` and `>>vasp_cmd<<` are hard-coded.

2021-03-30 02:49 UTC, bocklund commented on dfttk/EVcheck_QHA.py
> +        #vasp_db = VaspCalcDb.from_db_file(db_file, admin = True)
Commented code and hardcoded `>>db_file<<`.

2021-03-30 02:49 UTC, bocklund commented on dfttk/EVcheck_QHA.py
> +                                                        tolerance = tolerance, threshold = 14, vol_spacing = vol_spacing, vasp_cmd = ">>vasp_cmd<<", pass_isif4=pass_isif4,
More hardcoded `>>db_file<<` and `>>vasp_cmd<<`.

2021-03-30 02:49 UTC, bocklund commented on dfttk/ftasks.py
> +        #qha_result['has_phonon'] = self['phonon']
Please remove commented code.

2021-03-30 02:49 UTC, bocklund commented on dfttk/ftasks.py
> +        qha_result['has_phonon'] = num_phonons >= 5
Can you add a comment on why 5 is chosen here?

2021-03-30 02:49 UTC, bocklund commented on dfttk/ftasks.py
> +        num_phonons = len(list(vasp_db.db['phonon'].find({'$and':[ {'metadata.tag': tag}, {'adopted': True} ]})))
What's the purpose of `adopted`?  Is there a better name we could choose to be more clear about what it means given the context?

2021-03-30 02:49 UTC, bocklund commented on dfttk/ftasks.py
> +            # by Yi Wang, after a long day debug, finally I fixex the bug below
This line `# by Yi Wang, after a long day debug, finally I fixex the bug below` is not needed because it doesn't help anyone understand the code, but `sometimes the number of phonon volumes is less than that of static` is a good comment and helpful to understand what's happening.

2021-03-30 02:49 UTC, bocklund commented on dfttk/ftasks.py
> +        #if self['phonon']:
Please remove commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/input_sets.py
> +        kwargs.update({'user_incar_settings':RelaxSet.CONFIG['INCAR']})
Won't this overwrite all the settings with the ones from the `RelaxSet`? What's the goal of this change? More importantly, `user_*` settings should be reserved only for *users*. Any user settings *must* take precedence.

2021-03-30 02:49 UTC, bocklund commented on dfttk/input_sets.py
> +        #print ("xxxxxxxxx", kwargs)
Commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/pyphon.py
> +            #print ("pppppppppp", u0/eV)
Commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/pyphon.py
>      sound_ph : phonon seebeck corfficient (freq/k)
spelling error in `corfficient`

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
> +        #print("xxxxxxx", mu_el,mu_old)
Commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
> +            #print("db_file", sorted(volumes_b))
Commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
> +    def get_btp2(self, btp2_dir):
Please add a docstring to describe what this does with the arguments

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
>              if not os.path.exists(dir): continue
Commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
> +            #raise ValueError()
Should we continue raising a `ValueError` here so a user could track down the line of code that triggered this error?

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
>          if len(self.Vlat)!=len(self.volumes):
We should avoid printing warning information and instead use Python's built-in `warnings.warn` function

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
> +            print("\nFETAL ERROR! It appears that the calculations are not all done!\n")
Mispelling in `FETAL`. This should also raise a proper exception and avoid printing debugging info `print("xxx...`

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
> +            #if vol_within (vol, volumes):
Commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
> +            #print(lattices)
Remove commented debugging code

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
> +                #print ("xxxxxx=", self.formula_pretty)
Commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
> +        #self.volumes = np.array(list(map(float,sorted(volumes))))
Commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
> +                #print("xxxx=", self.qha_items, self.everyT)
Commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
> +                    print ("\nWARNING! I cannot find required data from qha_phonon, am asking help from Yphon!\n")
Should use a Python warning

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
>          #    fvol = open(self.phasename+'/fvol', "w")
Commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythelec.py
> +                #added by Yi Wang 09/24/2020
Unnecessary comment

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythfind.py
> +
Consider whether this should be deleted (and if so, remove commented code)

2021-03-30 02:49 UTC, bocklund commented on dfttk/pythfind.py
> +            #print ('db_file', mm)
Remove commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/scripts/PBS_template_custom.txt
> +export UCX_TLS=all
Does the existing PBS template from Fireworks have a `$${pre_rocket}` field or something similar? If so, these should be configured in the `my_fworker.yaml` file that we generate for users. Otherwise this will be guaranteed to break for all PBS systems that don't have exactly these modules. Whereas if we pre-generate them, a user can change them if they want to use a different system than the one these are supported on.

2021-03-30 02:49 UTC, bocklund commented on dfttk/scripts/config_dfttk.py
> +                "pre_rocket": "module load intel impi vasp",
Here's the pre-rocket 😁 - we probably don't need our own PBS template. Just add the additional commands here.

2021-03-30 02:49 UTC, bocklund commented on dfttk/scripts/config_dfttk.py
> +    #homepath = os.environ["HOME"]
Can you comment on the difference between these? Why use `Path.home()`?

2021-03-30 02:49 UTC, bocklund commented on dfttk/scripts/config_dfttk.py
> +    if os.path.exists (bashrc):
(style) Function names should not have a space between the name and the parenthesis

2021-03-30 02:49 UTC, bocklund commented on dfttk/scripts/config_dfttk.py
> +    from pathlib import Path
pathlib import should be at top level. It is also used in other places, which should all use the top level import.

2021-03-30 02:49 UTC, bocklund commented on dfttk/scripts/config_dfttk.py
> +    #print("ppppp")
Remove commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/scripts/config_dfttk.py
> +    from pathlib import Path
Path import that needs to be moved out of the function

2021-03-30 02:49 UTC, bocklund commented on dfttk/scripts/querydb.py
> +                #    print('The data in {} collection is removed'.format(collectioni))
Why is this commented? Isn't the purpose of this function to remove the data?

2021-03-30 02:49 UTC, bocklund commented on dfttk/structure_builders/sqs.py
> +                #temp = pmg.Element(component).data['Density of solid']
Remove commented code

2021-03-30 02:49 UTC, bocklund commented on dfttk/wflows.py
> +os.environ["HOME"] = str(Path.home())
Do we really want to set environment variables here?

2021-03-30 02:49 UTC, bocklund commented on docs/source/Installation.rst
> -    git clone https://github.com/PhasesResearchLab/dfttk.git
Should be cloning from PhasesResearchLab, not yiwang62

2021-03-30 02:49 UTC, bocklund commented on docs/source/Installation.rst
> +Note for ACI/roar in Penn State, download the file `PBS_template_custom.txt <https://github.com/yiwang62/dfttk/tree/20210211/dfttk/scripts>`_ into config/. Then
This instruction might need to be removed, since we should be using pre_rocket instead. If we must keep this, the link should point towards PhasesResearchLab, not yiwang62

2021-03-30 02:49 UTC, bocklund commented on docs/source/conf.py
> +release = 'beta 0.3.4'
This is not a valid version identifier. The [pre-releases section of PEP 440](https://www.python.org/dev/peps/pep-0440/#pre-releases) describes how to write beta version identifiers

2021-03-30 02:49 UTC, bocklund commented on docs/source/troubleshooting.rst
> +You mag meet numpy version issues using pymatgen, reporting::
Typo in `mag`

2021-03-30 02:49 UTC, bocklund commented on docs/source/troubleshooting.rst
> +This is due to ``conda`` bug on namespace of ruamel_yaml vs ruamel.yaml. It takes me a week to find out the solution. One can resolve this by open the Annaconda Powershell Prompt as adminstrator and
Please remove `It takes me a week to find out the solution. `, since this is not relevant to a reader

2021-03-30 02:49 UTC, bocklund commented on pytest.ini
> +    QHA_failure:
Are these markers necessary?

2021-03-30 02:49 UTC, bocklund commented on tests/db.json
> +    "port": 27018,
The tests *should* use a local database. We should not depend on our production database for tests (or leak the credentials! these should be changed ASAP)

2021-03-30 02:49 UTC, bocklund commented on tests/prl_test_utils.py
> +args, unknown = parser.parse_known_args()
What is `unknown`? And please remove any commented out code.

2021-03-30 02:49 UTC, bocklund commented on tests/test_EVcheck_QHA.py
> +    """
Why is this string added?

2021-03-30 02:52 UTC, bocklund commented on tests/test_thfind.py
> +class _thargs:
Similarly, this class is not testing DFTTK properly. If the defaults change, then this class will override the defaults and the test will not fail when it should.

2021-03-30 15:57 UTC, bocklund commented
@yiwang62 let me know when you have addressed everything and when this is ready for another round of review

2021-04-02 15:07 UTC, bocklund commented on dfttk/ftasks.py
> +            self.vasp_db.db['xmlgz'].insert_one(xml_data)
Is this inserting the `vasprun.xml` files into the database?

2021-04-02 17:02 UTC, yiwang62 commented
Brandon,

 

Yes, I am working on it.

 

Yi

 

From: Brandon Bocklund ***@***.***> 
Sent: Friday, April 2, 2021 11:08
To: PhasesResearchLab/dfttk ***@***.***>
Cc: Yi Wang ***@***.***>; Mention ***@***.***>
Subject: Re: [PhasesResearchLab/dfttk] accumulative bug fix (#1)

 

@bocklund commented on this pull request.

  _____  

In dfttk/ftasks.py <https://github.com/PhasesResearchLab/dfttk/pull/1#discussion_r606278493> :

> +    def run_task(self, fw_spec):
+        self.xml = self.get("xml", None)
+        if self.xml is not None:
+            fp = open(self.xml,"r")
+            with open (self.xml, 'r') as f:
+                xmldata = f.readlines()>>> data = fp.read()
+            bindata = gzip.compress(xmldata)
+            #with gzip.open("zen.txt.gz", "wb") as f:
+            #f.write(bindata)
+            self.db_file = env_chk(self.get("db_file"), fw_spec)
+            self.vasp_db = VaspCalcDb.from_db_file(self.db_file, admin=True)
+
+            structure = self.get('structure', Structure.from_file('POSCAR'))
+
+            xml_data = {'metadata': {'tag': self.get('tag')},
+                       'type': self.xml,
+                       'xmldata': bson.Binary(pickle.dumps(bindata)),
+                       'volume': structure.volume,
+                       'last_updated':datetime.datetime.utcnow(),
+                       'structure': structure.as_dict(),
+                       'formula_pretty': structure.composition.reduced_formula}
+            self.vasp_db.db['xmlgz'].insert_one(xml_data) 

Is this inserting the vasprun.xml files into the database?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/PhasesResearchLab/dfttk/pull/1#pullrequestreview-627036074> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AETO2PUM2LSNCBBYSVMIZ5TTGXMTRANCNFSM4Z7S26WQ> .

2021-04-02 18:00 UTC, bocklund commented on dfttk/ftasks.py
> +            self.vasp_db.db['xmlgz'].insert_one(xml_data)
I would strongly advise against adding the entire `vasprun.xml` into the database for a few reasons:

1. The files can get really big (like 500 MB for phonon calculations)
2. Much of the information is redundant with information extracted elsewhere
3. It makes it more difficult for a user to post-process the data, since they have to go through the hierarchy of the `vasprun.xml` file

The preferred solution is to extract what you need from the `vasprun.xml` file after the calculation and save that in the database, like what is done for all other calculations

2021-04-02 18:15 UTC, yiwang62 commented
Brandon,

 

Thanks for the comments!

I figured out the solution that only save that from static calculations. By gzip compression, the test calculation shows that it costed 500k. The purpose is for thermoelectric calculations which needs the complete vasprun.xml. I may add an option in the SETTING.yaml to save it

 

Yi

 

From: Brandon Bocklund ***@***.***> 
Sent: Friday, April 2, 2021 14:01
To: PhasesResearchLab/dfttk ***@***.***>
Cc: Yi Wang ***@***.***>; Mention ***@***.***>
Subject: Re: [PhasesResearchLab/dfttk] accumulative bug fix (#1)

 

@bocklund commented on this pull request.

  _____  

In dfttk/ftasks.py <https://github.com/PhasesResearchLab/dfttk/pull/1#discussion_r606351298> :

> +    def run_task(self, fw_spec):
+        self.xml = self.get("xml", None)
+        if self.xml is not None:
+            fp = open(self.xml,"r")
+            with open (self.xml, 'r') as f:
+                xmldata = f.readlines()>>> data = fp.read()
+            bindata = gzip.compress(xmldata)
+            #with gzip.open("zen.txt.gz", "wb") as f:
+            #f.write(bindata)
+            self.db_file = env_chk(self.get("db_file"), fw_spec)
+            self.vasp_db = VaspCalcDb.from_db_file(self.db_file, admin=True)
+
+            structure = self.get('structure', Structure.from_file('POSCAR'))
+
+            xml_data = {'metadata': {'tag': self.get('tag')},
+                       'type': self.xml,
+                       'xmldata': bson.Binary(pickle.dumps(bindata)),
+                       'volume': structure.volume,
+                       'last_updated':datetime.datetime.utcnow(),
+                       'structure': structure.as_dict(),
+                       'formula_pretty': structure.composition.reduced_formula}
+            self.vasp_db.db['xmlgz'].insert_one(xml_data) 

I would strongly advise against adding the entire vasprun.xml into the database for a few reasons:

1.	The files can get really big (like 500 MB for phonon calculations)
2.	Much of the information is redundant with information extracted elsewhere
3.	It makes it more difficult for a user to post-process the data, since they have to go through the hierarchy of the vasprun.xml file

The preferred solution is to extract what you need from the vasprun.xml file after the calculation and save that in the database, like what is done for all other calculations

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/PhasesResearchLab/dfttk/pull/1#discussion_r606351298> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AETO2PQO2P2NSPXWOMESOITTGYA5PANCNFSM4Z7S26WQ> .  <https://github.com/notifications/beacon/AETO2PUFYWSEHAT4BZRIWZDTGYA5PA5CNFSM4Z7S26W2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOEVQZYBI.gif>

2021-04-02 18:44 UTC, bocklund commented on dfttk/ftasks.py
> +            self.vasp_db.db['xmlgz'].insert_one(xml_data)
> Thanks for the comments!

> I figured out the solution that only save that from static calculations. By gzip compression, the test calculation shows that it costed 500k. The purpose is for thermoelectric calculations which needs the complete vasprun.xml. I may add an option in the SETTING.yaml to save it

Maybe the data needed for the thermoelectric calculations can be saved separately? What is needed from the vasprun beyond what is saved already?

2021-04-02 19:22 UTC, yiwang62 commented
Brandon,

 

I did not investigate what is read by the BoltzTraP2 code which do only need vasprun.xml

 

Best,

 

Yi

 

From: Brandon Bocklund ***@***.***> 
Sent: Friday, April 2, 2021 14:44
To: PhasesResearchLab/dfttk ***@***.***>
Cc: Yi Wang ***@***.***>; Mention ***@***.***>
Subject: Re: [PhasesResearchLab/dfttk] accumulative bug fix (#1)

 

@bocklund commented on this pull request.

  _____  

In dfttk/ftasks.py <https://github.com/PhasesResearchLab/dfttk/pull/1#discussion_r606368365> :

> +    def run_task(self, fw_spec):
+        self.xml = self.get("xml", None)
+        if self.xml is not None:
+            fp = open(self.xml,"r")
+            with open (self.xml, 'r') as f:
+                xmldata = f.readlines()>>> data = fp.read()
+            bindata = gzip.compress(xmldata)
+            #with gzip.open("zen.txt.gz", "wb") as f:
+            #f.write(bindata)
+            self.db_file = env_chk(self.get("db_file"), fw_spec)
+            self.vasp_db = VaspCalcDb.from_db_file(self.db_file, admin=True)
+
+            structure = self.get('structure', Structure.from_file('POSCAR'))
+
+            xml_data = {'metadata': {'tag': self.get('tag')},
+                       'type': self.xml,
+                       'xmldata': bson.Binary(pickle.dumps(bindata)),
+                       'volume': structure.volume,
+                       'last_updated':datetime.datetime.utcnow(),
+                       'structure': structure.as_dict(),
+                       'formula_pretty': structure.composition.reduced_formula}
+            self.vasp_db.db['xmlgz'].insert_one(xml_data) 

Thanks for the comments!

I figured out the solution that only save that from static calculations. By gzip compression, the test calculation shows that it costed 500k. The purpose is for thermoelectric calculations which needs the complete vasprun.xml. I may add an option in the SETTING.yaml to save it

Maybe the data needed for the thermoelectric calculations can be saved separately? What is needed from the vasprun beyond what is saved already?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/PhasesResearchLab/dfttk/pull/1#discussion_r606368365> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AETO2PV6VCYY6ELY4KCJC6LTGYGAPANCNFSM4Z7S26WQ> .  <https://github.com/notifications/beacon/AETO2PT733MNRUL6W3J6EFDTGYGAPA5CNFSM4Z7S26W2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOEVRF76Y.gif>

2021-04-02 19:48 UTC, bocklund commented on dfttk/ftasks.py
> +            self.vasp_db.db['xmlgz'].insert_one(xml_data)
> I did not investigate what is read by the BoltzTraP2 code which do only need vasprun.xml

I think Atomate has a BoltzTraP2 Firework - have you checked how they do it? I think they probably process the data and save it without storing the `vasprun.xml` file.

2021-04-02 19:50 UTC, bocklund commented on dfttk/ftasks.py
> +            self.vasp_db.db['xmlgz'].insert_one(xml_data)
Even so, I think this pull request is probably large enough without adding a bunch of new code for running BoltzTraP2. It was difficult to review before that. It's best to have PRs as close to a single logical change as possible, so adding BoltzTraP2 support for thermoelectric properties should be a separate pull request.

2021-04-02 21:10 UTC, yiwang62 commented
Brandon,

I turned if off by default.

Yi

From: Brandon Bocklund ***@***.***>
Reply-To: PhasesResearchLab/dfttk ***@***.***>
Date: Friday, April 2, 2021 at 3:50 PM
To: PhasesResearchLab/dfttk ***@***.***>
Cc: Yi Wang ***@***.***>, Mention ***@***.***>
Subject: Re: [PhasesResearchLab/dfttk] accumulative bug fix (#1)


@bocklund commented on this pull request.

________________________________

In dfttk/ftasks.py<https://github.com/PhasesResearchLab/dfttk/pull/1#discussion_r606393129>:

> +    def run_task(self, fw_spec):

+        self.xml = self.get("xml", None)

+        if self.xml is not None:

+            fp = open(self.xml,"r")

+            with open (self.xml, 'r') as f:

+                xmldata = f.readlines()>>> data = fp.read()

+            bindata = gzip.compress(xmldata)

+            #with gzip.open("zen.txt.gz", "wb") as f:

+            #f.write(bindata)

+            self.db_file = env_chk(self.get("db_file"), fw_spec)

+            self.vasp_db = VaspCalcDb.from_db_file(self.db_file, admin=True)

+

+            structure = self.get('structure', Structure.from_file('POSCAR'))

+

+            xml_data = {'metadata': {'tag': self.get('tag')},

+                       'type': self.xml,

+                       'xmldata': bson.Binary(pickle.dumps(bindata)),

+                       'volume': structure.volume,

+                       'last_updated':datetime.datetime.utcnow(),

+                       'structure': structure.as_dict(),

+                       'formula_pretty': structure.composition.reduced_formula}

+            self.vasp_db.db['xmlgz'].insert_one(xml_data)

Even so, I think this pull request is probably large enough without adding a bunch of new code for running BoltzTraP2. It was difficult to review before that. It's best to have PRs as close to a single logical change as possible, so adding BoltzTraP2 support for thermoelectric properties should be a separate pull request.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/PhasesResearchLab/dfttk/pull/1#discussion_r606393129>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AETO2PSVHCCH5QB2VL2SLRDTGYNYDANCNFSM4Z7S26WQ>.

2021-04-05 01:24 UTC, bocklund commented
@yiwang62 can you list the tasks left before this pull request can be merged? I’d like to define a cutoff point so that we can get you changes so far merged into DFTTK ASAP and then start working on another pull request with new additions or changes.

2021-04-05 14:22 UTC, yiwang62 commented
> @yiwang62 can you list the tasks left before this pull request can be merged? I’d like to define a cutoff point so that we can get you changes so far merged into DFTTK ASAP and then start working on another pull request with new additions or changes.

I almost finished the following
1.	Example documentation and have Shuang tried/passed the example
2.	Working on pytest for known failure cases
3.	the qha/phonopy failure issue
4.	resolve the AFM problem using Cr
5.     fix codes on all your comments

The coming tasks

refine non-selfconsistent calculation for DOS and vasprun.xml for thermoelectric. I

2021-04-09 04:28 UTC, bocklund commented
@yiwang62, please re-request my review when you are ready (right sidebar near the top of the pull request)

2021-04-09 13:03 UTC, yiwang62 commented
Brandon,

 

Do you mean clicking “Compare”  on www.github.com <http://www.github.com>  ?

 

Yi

 

From: Brandon Bocklund ***@***.***> 
Sent: Friday, April 9, 2021 0:29
To: PhasesResearchLab/dfttk ***@***.***>
Cc: Yi Wang ***@***.***>; Mention ***@***.***>
Subject: Re: [PhasesResearchLab/dfttk] accumulative bug fix (#1)

 

@yiwang62 <https://github.com/yiwang62> , please re-request my review when you are ready (right sidebar near the top of the pull request)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/PhasesResearchLab/dfttk/pull/1#issuecomment-816392661> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AETO2PSDSYEZ7WLUXETEQ3TTHZ67LANCNFSM4Z7S26WQ> .  <https://github.com/notifications/beacon/AETO2PRZS3EVIM2MESTTUOLTHZ67LA5CNFSM4Z7S26W2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGCUSTVI.gif>

2021-04-09 13:46 UTC, bocklund commented
<img width="1148" alt="Screen Shot 2021-04-09 at 9 45 19 AM" src="https://user-images.githubusercontent.com/7681751/114189717-7f5d0700-9918-11eb-9f25-708e3ba7dddf.png">

2021-04-11 19:27 UTC, bocklund requested changes

2021-04-11 19:27 UTC, bocklund commented on dfttk/EVcheck_QHA.py
> +        vasp_cmd = ">>vasp_cmd<<"
Hardcoded "`>>vasp_cmd<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/EVcheck_QHA.py
> +                                           prev_calc_loc=False, vasp_input_set=vis_prestatic, vasp_cmd=">>vasp_cmd<<", db_file=db_file,
Hardcoded "`>>vasp_cmd<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/EVcheck_QHA.py
> +                                                        tolerance = tolerance, threshold = 14, vol_spacing = vol_spacing, vasp_cmd = ">>vasp_cmd<<", pass_isif4=pass_isif4,
Hardcoded "`>>vasp_cmd<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/EVcheck_QHA.py
> +                                               prev_calc_loc=False, vasp_input_set=vis_relax, vasp_cmd=">>vasp_cmd<<", db_file=db_file,
Hardcoded "`>>vasp_cmd<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/EVcheck_QHA.py
> +                                                    threshold = threshold, vol_spacing = vol_spacing, vasp_cmd = ">>vasp_cmd<<", run_num = run_num,
Hardcoded "`>>vasp_cmd<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/analysis/ywutils.py
>    #print("eeeeee", formula, ele, com)
Commented code

2021-04-11 19:27 UTC, bocklund commented on dfttk/fworks.py
> +        t.append(CheckSymmetryToDb(db_file=">>db_file<<", tag=tag, override_symmetry_tolerances=override_symmetry_tolerances, site_properties=site_properties))
Hardcoded "`>>db_file<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/fworks.py
> +        t.append(CheckRelaxation(db_file=">>db_file<<", metadata=metadata, tag=tag, isif4=isif4, level=level, energy_with_isif=energy_with_isif,
Hardcoded "`>>db_file<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/fworks.py
> +        t.append(CheckSymmetryToDb(db_file=">>db_file<<", tag=tag, site_properties=site_properties))
Hardcoded "`>>db_file<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/fworks.py
> +        t.append(Record_relax_running_path(db_file = ">>db_file<<", metadata = metadata, run_isif2=run_isif2, pass_isif4=pass_isif4))
Hardcoded "`>>db_file<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/fworks.py
> +        t.append(PhononStable(supercell_matrix=supercell_matrix, db_file=">>db_file<<", tag=tag, metadata=metadata, qpoint_mesh=qpoint_mesh, stable_tor=stable_tor))
Hardcoded "`>>db_file<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/fworks.py
> +        t.append(BornChargeToDb(db_file=">>db_file<<", tag=tag))
Hardcoded "`>>db_file<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/pythelec.py
> +                    #(T[i], F_el_atom[i], S_el_atom[i], C_el_atom[i], M_el[i], seebeck_coefficients[i], L,
Commented out code.

2021-04-11 19:27 UTC, bocklund commented on dfttk/pythelec.py
>          #    readme['Helmholtz energy quality'] = '+-{} eV'.format(9999)
Commented out code

2021-04-11 19:27 UTC, bocklund commented on dfttk/pythelec.py
> +        #print (self.key_comments)
Commented out code

2021-04-11 19:27 UTC, bocklund commented on dfttk/pythelec.py
> +                    sys.exit()
Is this expected? It will always run, print, and exit.

2021-04-11 19:27 UTC, bocklund commented on dfttk/scripts/config_dfttk.py
> +    #Path.home() is better that os.environ["HOME"]
We should do this instead of `PATH` and `os.environ`: https://stackoverflow.com/a/14742225/5106932

2021-04-11 19:27 UTC, bocklund commented on dfttk/scripts/config_dfttk.py
> +    homepath = str(Path.home())
Another usage of `Path`. See the other comment and make sure to grep for other usages please.

2021-04-11 19:27 UTC, bocklund commented on dfttk/scripts/run_dfttk.py
> +        db_file = ">>db_file<<"
Hardcoded `">>db_file<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/scripts/run_dfttk.py
> +                 eos_tolerance=eos_tolerance, volume_spacing_min=volume_spacing_min, vasp_cmd=">>vasp_cmd<<", db_file=">>db_file<<",
Hardcoded `">>db_file<<"` and `">>vasp_cmd<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/scripts/run_dfttk.py
> +        wf = get_wf_borncharge(structure=structure, metadata=metadata, db_file=">>db_file<<", isif=2, name="born charge",
Hardcoded `">>db_file<<"` and `">>vasp_cmd<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/scripts/run_dfttk_ext.py
>  #from dfttk.wflows import get_wf_gibbs, get_wf_EV_bjb, get_wf_gibbs_robust
commented imports

2021-04-11 19:27 UTC, bocklund commented on dfttk/scripts/run_dfttk_ext.py
> +    global no_MongoDB
Please reconsider introducing global variables

2021-04-11 19:27 UTC, bocklund commented on dfttk/scripts/run_dfttk_ext.py
> +        #print("xxxxxxxxxxxx",readme)
Please remove commented code

2021-04-11 19:27 UTC, bocklund commented on dfttk/scripts/run_dfttk_ext.py
> +        #print("xxxxxxxxxx", plotfiles)
Please remove all commented code

2021-04-11 19:27 UTC, bocklund commented on dfttk/utils.py
>      from atomate.vasp.database import VaspCalcDb
Hardcoded `">>db_file<<"` and `">>vasp_cmd<<"`

2021-04-11 19:27 UTC, bocklund commented on dfttk/wflows.py
> +os.environ["HOME"] = str(Path.home())
Please prefer `os.path.expanduser('~')` and don't set environment variables, especially not something as critical as `HOME`.

https://stackoverflow.com/a/14742225/5106932

2021-04-11 19:27 UTC, bocklund commented on qha_summary.json
> +                    1.36689,
Please delete this file.

2021-04-11 19:27 UTC, bocklund commented on tests/test_thfind.py
> +import argparse
Remove commented code

2021-04-11 19:27 UTC, bocklund commented on tests/test_utils.py
> +    #assert(formula == ['CrFe3', 'Cr2Fe', 'CrFe3', 'Cr3Fe', 'CrFe4', 'CrFe', 'Cr3Fe', 'Cr3Fe'])
Commented code

2021-04-11 19:28 UTC, bocklund commented
@yiwang62 please see the request changed on GitHub and address them all. Once you make the changes, I will mark each one as resolved and you can feel free to ask questions or discuss more in each sub conversation

<img width="1152" alt="Screen Shot 2021-04-11 at 3 27 21 PM" src="https://user-images.githubusercontent.com/7681751/114318275-6b610300-9ada-11eb-9a91-3e5cae85222e.png">

2021-06-28 14:13 UTC, closed without merging

2021-06-28 14:14 UTC, yiwang62 commented
I will redo the pull request for incorporate all recent update