pull request for merging changes on Debye model
PhasesResearchLab/dfttk-2021 pull request #8
Opened 2021-07-12 13:37 UTC by yiwang62

2021-07-15 20:19 UTC, bocklund requested changes

2021-07-15 20:19 UTC, bocklund commented on dfttk/analysis/debye.py
> +        Eq(4) in doi.org/10.1016/j.comphy.2003.12.001
`Eq(4) in doi.org/10.1016/j.comphy.2003.12.001` seems to be copied from the Helmholtz energy and it doesn't refer to the vibrational entropy.

2021-07-15 20:19 UTC, bocklund commented on dfttk/analysis/debye.py
> +            float: vibrational entropy in eV
Units need updating

2021-07-15 20:19 UTC, bocklund commented on dfttk/analysis/debye.py
> +        Eq(4) in doi.org/10.1016/j.comphy.2003.12.001
`Eq(4) in doi.org/10.1016/j.comphy.2003.12.001` seems to be copied from the Helmholtz energy and it doesn't refer to the vibrational heat capacity.

2021-07-15 20:19 UTC, bocklund commented on dfttk/analysis/debye.py
> +            #print ("DebyeT=", self.debye_temperature(vol))
```suggestion
```

2021-07-15 20:19 UTC, bocklund commented on dfttk/analysis/debye.py
> +                #print ("CT=", self.vibrational_heat_capacity(temp, vol))
```suggestion
```

2021-07-15 20:19 UTC, bocklund commented on dfttk/analysis/debye.py
> +            integral = quadrature(lambda x: x ** 4 *np.exp(x)/ (np.exp(x) - 1.)**2, 0, y)
Does the limit of `155` in `y < 155` make sense to use here? In the `debye_integral` method, as the comment suggests, it was introduced for numerical stability of the integral. However, since the integral changes in this method, should the limit also be reconsidered?

2021-07-15 20:19 UTC, bocklund commented on dfttk/analysis/debye.py
> +        pi=math.pi
```suggestion
        pi = math.pi
```

2021-07-15 20:19 UTC, bocklund commented on dfttk/analysis/debye.py
> +        pi=math.pi
Since you already import scipy, it might make sense to use pi from scipy, rather than from math (avoiding the extra import)

2021-07-15 20:19 UTC, bocklund commented on dfttk/analysis/debye.py
> +        #debye = 2.9772e-11 * (volume / self.natoms) ** (-1. / 6.) * s * np.sqrt(self.bulk_modulus/self.avg_mass)
```suggestion
```

2021-07-15 20:19 UTC, bocklund commented on dfttk/analysis/debye.py
> +        debye = s*A * (volume*1.e-30/self.natoms) ** (1. / 6.) * np.sqrt(self.bulk_modulus*1e9/self.avg_mass)
This could be a good place for an automated test specifically to check that the Debye temperature is equal to some known value within tolerance (via `np.isclose`).

2021-07-15 20:19 UTC, bocklund commented on dfttk/analysis/quasiharmonic.py
>  #from dfttk.analysis.debye import DebyeModel
```suggestion
```

2021-07-19 15:20 UTC, yiwang62 commented on dfttk/analysis/debye.py
> +        Eq(4) in doi.org/10.1016/j.comphy.2003.12.001
The comments are just copy and I have changed it

2021-07-19 15:20 UTC, yiwang62 commented on dfttk/analysis/debye.py
> +            float: vibrational entropy in eV
change eV/K

2021-07-19 15:21 UTC, yiwang62 commented on dfttk/analysis/debye.py
> +        Eq(4) in doi.org/10.1016/j.comphy.2003.12.001
updated

2021-07-19 15:21 UTC, yiwang62 commented on dfttk/analysis/debye.py
> +            #print ("DebyeT=", self.debye_temperature(vol))
deleted

2021-07-19 15:22 UTC, yiwang62 commented on dfttk/analysis/debye.py
> +                #print ("CT=", self.vibrational_heat_capacity(temp, vol))
deleted

2021-07-19 15:26 UTC, yiwang62 commented on dfttk/analysis/debye.py
> +            integral = quadrature(lambda x: x ** 4 *np.exp(x)/ (np.exp(x) - 1.)**2, 0, y)
155 should be fine which means when T > 155/theta, numerical integration. Otherwise, low T expansion.
By the calculations Cp and S, it appears 155 is a good value

2021-07-19 15:33 UTC, yiwang62 commented on dfttk/analysis/debye.py
> +        pi=math.pi
Thanks! I changed into scipy

2021-07-19 15:36 UTC, yiwang62 commented on dfttk/analysis/debye.py
> +        debye = s*A * (volume*1.e-30/self.natoms) ** (1. / 6.) * np.sqrt(self.bulk_modulus*1e9/self.avg_mass)
working on it

2021-07-19 15:38 UTC, yiwang62 commented on dfttk/analysis/quasiharmonic.py
>  #from dfttk.analysis.debye import DebyeModel
update

2021-07-26 15:52 UTC, bocklund commented
@yiwang62 please feel free to re-request a review via the GitHub UI when you are finished making changes

2021-08-11 21:05 UTC, bocklund approved these changes

2021-08-12 13:59 UTC, merged